os:
  - osx

language: node_js
node_js:
  "8"

install:
  - yarn install

script:
  - yarn lint
  - yarn test:all --coverage
  - ./node_modules/.bin/coveralls < ./coverage/lcov.info
  - yarn build
  - yarn package:publish