os:
  - osx

language: node_js
node_js:
  "8"

install:
  - yarn install

script:
  - yarn lint
  - yarn test:all
  - yarn test:unit --coverage
  - yarn coverage
  - yarn bundle
  - yarn package:publish