image: Visual Studio 2017

environment:
  nodejs_version: "12"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - yarn install

before_build:
  - set NODE_ENV=production

build_script:
  - yarn tsc:validate
  - yarn lint
  - yarn bundle
  - yarn test

test: off