image: Visual Studio 2017

environment:
  nodejs_version: "8"
  NODE_ENV: production

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - yarn install

build_script:
  - yarn tsc:validate
  - yarn lint
  - yarn bundle
  - yarn test

test: off