directories:
  output: dist
  buildResources: bundle

files:
  - bundle/**/*.js
  - styles/**/*.css
  - ./*.html
  - img/**/*
  - assets/**/*

win:
  icon: ./img/icons/win/ueli-black-on-white-logo.ico
  target:
    - nsis
    - zip
  publish:
    - github

mac:
  icon: ./img/icons/mac/ueli-black-on-white-logo.icns
  category: public.app-category.utilities
  target:
    - dmg
    - zip
  publish:
    - github

nsis:
  allowToChangeInstallationDirectory: true
  oneClick: false
  perMachine: true