on: [push]

jobs:
  test:
    name: Test, lint and build the app on node ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12]
        os: [windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
      env:
        NODE_ENV: production

    - name: Install dependencies
      run: |
        yarn install
        
    - name: Validate and lint TypeScript files
      run: |
        yarn tsc:validate
        yarn lint
        
    - name: Bundle files
      run: |
        yarn bundle
        
    - name: Run tests
      run: |
        yarn test
        
    - name: Package and publish app
      run: |
        yarn package:publish
